name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - appmode=0.8.0
  - pandas=1.3.4
  - python=3.9.7
  - widgetsnbextension
  - dataframe_image
  - chromedriver
# prefix: C:\Anaconda
